# Generated by Django 4.2.1 on 2023-05-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NegativeWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PositiveWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_word', models.CharField(max_length=100)),
            ],
        ),
    ]
